### ISSUE TITLE
Capture stderr when running as agent

### ISSUE THREAD

**Issue by daonb** [tuzig/webexec#21]
When running as agent and webexec panics the report should be written to `~/.webexec/agent.log`

Today we set the command's stderr to `agent.err` but it's left empty, probably because the agent runs in the background and the err file is being closed when the cli exits.

**Comment by daonb** [comment]
Thanks for the code, but I when I change to `cmd.Run` to `cmd.Start` I lose the output.  when the user types `webexec start` the code starts the command `webexec start --agent` and exits immediately losing the Writers used for stderr & stdout.

**Comment by tebeka** [comment]
I *guess* it's a buffering issue.

**Comment by tebeka** [comment]
Or it might be due to the fact the agents tty is closed. Maybe the "double fork" trick is required.

**Comment by daonb** [comment]
My guess is that go adds system pipes to connect the reader and writer at both ends. When the parent process exits it's end of the pipe is broken and whatever the agent outputs goes nowhere. 
Maybe we need to fork at the unix level? Maybe go's implementation does not cover the agent/daemon use case.

**Comment by daonb** [comment]
@tebeka webexec just crashed and the trace is not to be found. Do you have time to fix this?

**Comment by tebeka** [comment]
I'll have a look. Can you specify the steps to reproduce the issue?

**Comment by daonb** [comment]
@tebeka just run the code you added above with `cmd.Start` instead of `cmd.Run`

**Comment by tebeka** [comment]
It's fail with `Start` since it won't wait for the command to terminate.
You need to call `cmd.Wait()` to wait for the sub process to terminate. If the program spinning the agent is done - the logger is no longer available.

**Comment by daonb** [comment]
I can't wait for it. I'm starting a background agent. As I was preparing the demo code for you I found out it does work. I've cleaned up the redirection and I'm now trying to crash It to make sure it's solved.

**Comment by daonb** [comment]
It's fixed.
