### ISSUE TITLE
Change control message time ISO format

### ISSUE THREAD

**Issue by daonb** [tuzig/webexec#22]
So it will look like: 2012-04-23T18:25:43.511Z

(from: https://stackoverflow.com/a/15952652/66595)

**Comment by tebeka** [comment]
If you'll use JSON as serialization format for the control messages. Then `time.Time` will automatically be serailzed as RFC3339

**Comment by daonb** [comment]
Seems like we're not using this and it's probably better to just remove it.

**Comment by daonb** [comment]
Going to remove the time field.
