### ISSUE TITLE
Support orderly disconnect & reconnect

### ISSUE THREAD

**Issue by daonb** [tuzig/webexec#39]
## The need

Client may go to sleep - like when a tablet app is switched to the background - and have no way of keeping communication open. Clients do get a notification when they are going to get "benched" and can recognise when they're back in the foreground.

During those  app switches the clients want to keep the appearance of being always connected and not lose a single char of output. Here's the flow we need to support:

1. Client gets notified of an app state change
2. client send's webexec  a close message, it's ack containing the restore token
...
3. client is back in the foreground
4. client reconnects, passing the restore token in the auth message
5. webexec receives the token and send all the new packets since the client was benched.

**Comment by tebeka** [comment]
IMO it'll be easier to have the server store lines in a database/file (one per pane?), each with a timestamp. The client should query the server for new lines since last check.
This way the client knows the last time.

**Comment by daonb** [comment]
You're right - a timestamp is much better than an index. 

You're solution complicates things for the normal scenario - when I click the keyboard and each char is sent over and back. I believe your solution will require us to send a timestamp with each char and add a protocol where today we have free flowing pipes.

**Comment by tebeka** [comment]
You can still save line oriented data - keep a buffer until newline and then save

**Comment by daonb** [comment]
The interesting thing is that if I publish the timestamp only as a response to a disconnect, I can store only those timestamps that I send. This allows me to keep all the bytes in a cyclic array and store the  array index of each sent timestamp.
