### ISSUE TITLE
Add the repo to awesome-pion

### ISSUE THREAD

**Issue by ynigun** [tuzig/webexec#74]
Maybe it will help bring in more contributors to the project if it will be in [awesome-pion](https://github.com/pion/awesome-pion)
maybe you can also write about it in [pion's Slack channel](https://pion.ly/slack) .

נ.ב. פשוט שמעתי על הפרוייקט ברברסים וזה מה שיש לי לתרום לבנתיים

**Comment by daonb** [comment]
Thanks! It's done. Regarding the slack channel, it's great and I've already posted the news there.
