### ISSUE TITLE
Add session management

### ISSUE THREAD

**Issue by daonb** [tuzig/webexec#9]
When the client authenticates, webexec should start a session process by: `su <username> -c "webexec session start" ` and use it to manage the sessions channels: start a channel, send it input, get output, resize and eventually, kill it. Our design goal is to keep the session manager process as small as possible using it  for the bare minimum that has to happen under the user's account.

The  communication between the main process and the session is done using stdin & stdout over a simple text based protocol. Each command is a single line of text made up from fields separated by space. The first field is a single letter denoting the requested command, followed by a channel id and additional fields based on the command.

## Received commands 

The following commands are sent by webexec main process to the session manager over stdin:

### Exec

`e 12345 80x24 htop`

This will cause the process to start a new process `htop` with a pty the size of 80x24. The last field can be omitted and the process will run the user's shell.

### Input

`i 12345 this is a line of input`

### Resize

`r 12345 160x48`

### Kill

`k 12345`

### Output

`o 12345 a line of output`

### Killed

`k 12345`

There are a few things that need to get done:

- [ ] Writing tests
- [ ] Handling command line arguments
- [ ] Coding the commands for `session start`
- [ ] main<->session protocol (using stdin, out & err)
- [ ] refactoring existing code so that on authentication it will exec the new command
- [ ]   `session list`
- [ ]   `session kill`

**Comment by tebeka** [comment]
I'd use an esablished serialization format like json or gob for communication.
